### ISSUE TITLE
stopped working on Ubuntu 18.04: TypeError: ExtensionUtils.initTranslations is not a function 

### ISSUE THREAD

**Issue by fallenguru** [emasab/shelltile#136]
ShellTile has recently stopped working properly on this installation of Ubuntu 18.04, gnome-shell 3.28.4-0ubuntu18.04.7 (X11). I seem to remember the extension being updated around that time.

Trying to enter settings gives:

```
TypeError: ExtensionUtils.initTranslations is not a function

Stack trace:
  buildPrefsWidget@/home/chris/.local/share/gnome-shell/extensions/ShellTile@emasab.it/prefs.js:24:9
  _selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:91:22
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:243:17
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:397:5
  @<main>:1:43
```

Could it be that backwards-compatibility was accidentally broken? I'd be really grateful if this were fixed, or alternatively the last known good version provided on extensions.gnome.org for 3.28.
